POST http://localhost:3000/api/goals
Content-Type: application/json
 
{
    "title": "Become a software developer"
}

########

GET http://localhost:3000/api/goals

########

GET http://localhost:3000/api/goals/5

########

PUT http://localhost:3000/api/goals/16
Content-Type: application/json
 
{
    "title": "Move out"
}

########

DELETE  http://localhost:3000/api/goals/1

########
