POST http://localhost:3000/goals
Content-Type: application/json
 
{
    "title": "Move out on my own"
}

########

GET http://localhost:3000/goals

########

GET http://localhost:3000/goals/4

########

DELETE  http://localhost:3000/goals/5

########
